import type { Plugin } from 'vite';
import fs from 'fs';
import path from 'path';

function findAllSvelteFiles(dir: string, fileList: string[] = []) {
	const files = fs.readdirSync(dir);
	files.forEach((file: string) => {
		const filePath = path.join(dir, file);
		const stat = fs.statSync(filePath);
		if (stat.isDirectory()) {
			if (file !== 'node_modules' && file !== '.svelte-kit') {
				findAllSvelteFiles(filePath, fileList);
			}
		} else {
			if (file.endsWith('.svelte')) {
				fileList.push(filePath);
			}
		}
	});
	return fileList;
}

function extractPortalNames(files: string[]) {
	const names = new Set<string>();
	const regex = /<Portal[^>]*\bname=(["'])(.*?)\1/g;

	files.forEach((file) => {
		const content = fs.readFileSync(file, 'utf-8');
		let match;
		while ((match = regex.exec(content)) !== null) {
			if (match[2]) {
				names.add(match[2]);
			}
		}
	});
	return Array.from(names);
}

function generateDts(names: string[]) {
	const union = names.map((n) => `'${n}': boolean`).join(';\n\t\t');
	return `// Auto-generated by svelte-bay
import 'svelte-bay';

declare module 'svelte-bay' {
	interface PortalRegistry {
		${union};
	}
}
`;
}

export function svelteBay(): Plugin {
	let root = process.cwd();

	const updateTypes = () => {
		try {
			const srcDir = path.join(root, 'src');
			if (!fs.existsSync(srcDir)) return;

			const files = findAllSvelteFiles(srcDir);
			const names = extractPortalNames(files);
			const dtsContent = generateDts(names);
			
			const typeDir = path.join(root, '.svelte-kit', 'types');
			if (!fs.existsSync(typeDir)) {
				fs.mkdirSync(typeDir, { recursive: true });
			}

			const dtsPath = path.join(typeDir, 'svelte-bay.d.ts');
			fs.writeFileSync(dtsPath, dtsContent);
		} catch (e) {
			console.error('[svelte-bay] Failed to update types:', e);
		}
	};

	return {
		name: 'svelte-bay-auto-types',
		configResolved(config) {
			root = config.root;
		},
		buildStart() {
			updateTypes();
		},
		handleHotUpdate({ file, server }) {
			if (file.endsWith('.svelte')) {
				updateTypes();
			}
		}
	};
}
